<?php

namespace ContainerKNGwNBx;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3z6RYkvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3z6RYkv' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3z6RYkv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\ApiAppController::easterEgg' => ['privates', '.service_locator.pDGtuzv.App\\Controller\\ApiAppController::easterEgg()', 'getApiAppControllereasterEggService', true],
            'App\\Controller\\ApiCategoriesController::getCategories' => ['privates', '.service_locator.j3q0Ln..App\\Controller\\ApiCategoriesController::getCategories()', 'getApiCategoriesControllergetCategoriesService', true],
            'App\\Controller\\ApiEventController::getEvents' => ['privates', '.service_locator.wxPd78M.App\\Controller\\ApiEventController::getEvents()', 'getApiEventControllergetEventsService', true],
            'App\\Controller\\ApiEventController::getEventById' => ['privates', '.service_locator.wxPd78M.App\\Controller\\ApiEventController::getEventById()', 'getApiEventControllergetEventByIdService', true],
            'App\\Controller\\ApiEventController::createEvent' => ['privates', '.service_locator.gocdo6Y.App\\Controller\\ApiEventController::createEvent()', 'getApiEventControllercreateEventService', true],
            'App\\Controller\\ApiEventController::updateEvent' => ['privates', '.service_locator.U_cLm5R.App\\Controller\\ApiEventController::updateEvent()', 'getApiEventControllerupdateEventService', true],
            'App\\Controller\\ApiEventController::deleteEvent' => ['privates', '.service_locator.f9eMvu1.App\\Controller\\ApiEventController::deleteEvent()', 'getApiEventControllerdeleteEventService', true],
            'App\\Controller\\ApiEventUserController::getUsersByEventId' => ['privates', '.service_locator.wxPd78M.App\\Controller\\ApiEventUserController::getUsersByEventId()', 'getApiEventUserControllergetUsersByEventIdService', true],
            'App\\Controller\\ApiImageController::upload' => ['privates', '.service_locator.anOmxmZ.App\\Controller\\ApiImageController::upload()', 'getApiImageControlleruploadService', true],
            'App\\Controller\\ApiUserController::getMe' => ['privates', '.service_locator.YOUPp1C.App\\Controller\\ApiUserController::getMe()', 'getApiUserControllergetMeService', true],
            'App\\Controller\\ApiUserController::createUser' => ['privates', '.service_locator.3PbG7Du.App\\Controller\\ApiUserController::createUser()', 'getApiUserControllercreateUserService', true],
            'App\\Controller\\ApiUserController::getUserById' => ['privates', '.service_locator.OzEre6h.App\\Controller\\ApiUserController::getUserById()', 'getApiUserControllergetUserByIdService', true],
            'App\\Controller\\ApiUserController::deleteUser' => ['privates', '.service_locator.anOmxmZ.App\\Controller\\ApiUserController::deleteUser()', 'getApiUserControllerdeleteUserService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\ApiAppController:easterEgg' => ['privates', '.service_locator.pDGtuzv.App\\Controller\\ApiAppController::easterEgg()', 'getApiAppControllereasterEggService', true],
            'App\\Controller\\ApiCategoriesController:getCategories' => ['privates', '.service_locator.j3q0Ln..App\\Controller\\ApiCategoriesController::getCategories()', 'getApiCategoriesControllergetCategoriesService', true],
            'App\\Controller\\ApiEventController:getEvents' => ['privates', '.service_locator.wxPd78M.App\\Controller\\ApiEventController::getEvents()', 'getApiEventControllergetEventsService', true],
            'App\\Controller\\ApiEventController:getEventById' => ['privates', '.service_locator.wxPd78M.App\\Controller\\ApiEventController::getEventById()', 'getApiEventControllergetEventByIdService', true],
            'App\\Controller\\ApiEventController:createEvent' => ['privates', '.service_locator.gocdo6Y.App\\Controller\\ApiEventController::createEvent()', 'getApiEventControllercreateEventService', true],
            'App\\Controller\\ApiEventController:updateEvent' => ['privates', '.service_locator.U_cLm5R.App\\Controller\\ApiEventController::updateEvent()', 'getApiEventControllerupdateEventService', true],
            'App\\Controller\\ApiEventController:deleteEvent' => ['privates', '.service_locator.f9eMvu1.App\\Controller\\ApiEventController::deleteEvent()', 'getApiEventControllerdeleteEventService', true],
            'App\\Controller\\ApiEventUserController:getUsersByEventId' => ['privates', '.service_locator.wxPd78M.App\\Controller\\ApiEventUserController::getUsersByEventId()', 'getApiEventUserControllergetUsersByEventIdService', true],
            'App\\Controller\\ApiImageController:upload' => ['privates', '.service_locator.anOmxmZ.App\\Controller\\ApiImageController::upload()', 'getApiImageControlleruploadService', true],
            'App\\Controller\\ApiUserController:getMe' => ['privates', '.service_locator.YOUPp1C.App\\Controller\\ApiUserController::getMe()', 'getApiUserControllergetMeService', true],
            'App\\Controller\\ApiUserController:createUser' => ['privates', '.service_locator.3PbG7Du.App\\Controller\\ApiUserController::createUser()', 'getApiUserControllercreateUserService', true],
            'App\\Controller\\ApiUserController:getUserById' => ['privates', '.service_locator.OzEre6h.App\\Controller\\ApiUserController::getUserById()', 'getApiUserControllergetUserByIdService', true],
            'App\\Controller\\ApiUserController:deleteUser' => ['privates', '.service_locator.anOmxmZ.App\\Controller\\ApiUserController::deleteUser()', 'getApiUserControllerdeleteUserService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\ApiAppController::easterEgg' => '?',
            'App\\Controller\\ApiCategoriesController::getCategories' => '?',
            'App\\Controller\\ApiEventController::getEvents' => '?',
            'App\\Controller\\ApiEventController::getEventById' => '?',
            'App\\Controller\\ApiEventController::createEvent' => '?',
            'App\\Controller\\ApiEventController::updateEvent' => '?',
            'App\\Controller\\ApiEventController::deleteEvent' => '?',
            'App\\Controller\\ApiEventUserController::getUsersByEventId' => '?',
            'App\\Controller\\ApiImageController::upload' => '?',
            'App\\Controller\\ApiUserController::getMe' => '?',
            'App\\Controller\\ApiUserController::createUser' => '?',
            'App\\Controller\\ApiUserController::getUserById' => '?',
            'App\\Controller\\ApiUserController::deleteUser' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\ApiAppController:easterEgg' => '?',
            'App\\Controller\\ApiCategoriesController:getCategories' => '?',
            'App\\Controller\\ApiEventController:getEvents' => '?',
            'App\\Controller\\ApiEventController:getEventById' => '?',
            'App\\Controller\\ApiEventController:createEvent' => '?',
            'App\\Controller\\ApiEventController:updateEvent' => '?',
            'App\\Controller\\ApiEventController:deleteEvent' => '?',
            'App\\Controller\\ApiEventUserController:getUsersByEventId' => '?',
            'App\\Controller\\ApiImageController:upload' => '?',
            'App\\Controller\\ApiUserController:getMe' => '?',
            'App\\Controller\\ApiUserController:createUser' => '?',
            'App\\Controller\\ApiUserController:getUserById' => '?',
            'App\\Controller\\ApiUserController:deleteUser' => '?',
        ]);
    }
}
