<?php

namespace ContainerKNGwNBx;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiAppControllereasterEggService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pDGtuzv.App\Controller\ApiAppController::easterEgg()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pDGtuzv.App\\Controller\\ApiAppController::easterEgg()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'errorHandler' => ['privates', 'App\\Service\\ApiErrorHandler', 'getApiErrorHandlerService', true],
        ], [
            'errorHandler' => 'App\\Service\\ApiErrorHandler',
        ]))->withContext('App\\Controller\\ApiAppController::easterEgg()', $container);
    }
}
