<?php

namespace ContainerKNGwNBx;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiUserControllerdeleteUserService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.anOmxmZ.App\Controller\ApiUserController::deleteUser()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.anOmxmZ.App\\Controller\\ApiUserController::deleteUser()'] = ($container->privates['.service_locator.anOmxmZ'] ?? $container->load('get_ServiceLocator_AnOmxmZService'))->withContext('App\\Controller\\ApiUserController::deleteUser()', $container);
    }
}
