<?php

namespace ContainerKNGwNBx;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiErrorHandlerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\ApiErrorHandler' shared autowired service.
     *
     * @return \App\Service\ApiErrorHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'ApiErrorHandler.php';

        return $container->privates['App\\Service\\ApiErrorHandler'] = new \App\Service\ApiErrorHandler();
    }
}
