<?php

namespace ContainerKNGwNBx;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiValidationUtilsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\ApiValidationUtils' shared autowired service.
     *
     * @return \App\Service\ApiValidationUtils
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'ApiValidationUtils.php';

        return $container->privates['App\\Service\\ApiValidationUtils'] = new \App\Service\ApiValidationUtils(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')));
    }
}
