<?php

namespace ContainerKNGwNBx;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiCategoriesControllergetCategoriesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.j3q0Ln..App\Controller\ApiCategoriesController::getCategories()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.j3q0Ln..App\\Controller\\ApiCategoriesController::getCategories()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'categoriesRepository' => ['privates', 'App\\Repository\\CategoryRepository', 'getCategoryRepositoryService', true],
        ], [
            'categoriesRepository' => 'App\\Repository\\CategoryRepository',
        ]))->withContext('App\\Controller\\ApiCategoriesController::getCategories()', $container);
    }
}
